FROM ubuntu:19.04

ENV LANG C.UTF-8

RUN apt-get update \
    && apt-get install -y build-essential python3-dev python3-pip python3-numpy-dev python3-six \
       libfftw3-3 libyaml-0-2 libtag1v5 libsamplerate0 python3-yaml \
       libavcodec58 libavformat58 libavutil56 libavresample4 wget pkg-config libeigen3-dev\
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip setuptools \
    && pip3 install --no-cache-dir tensorflow==1.15.0

RUN apt-get update \
    && apt-get install -y build-essential git \
    && mkdir /essentia && mkdir -p /usr/local/lib/pkgconfig \
    && cd /essentia && git clone https://github.com/MTG/essentia.git \
    && cd /essentia/essentia && src/3rdparty/tensorflow/setup_from_python.sh \ 
    && python3 waf configure --build-static --with-python --with-examples --with-vamp --with-tensorflow \
    && python3 waf && python3 waf install && ldconfig \
    && apt-get remove -y build-essential libyaml-dev libfftw3-dev libavcodec-dev \
       libavformat-dev libavutil-dev libavresample-dev python-dev libsamplerate0-dev \
       libtag1-dev python3-numpy-dev \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && cd / && rm -rf /essentia/essentia

ENV PYTHONPATH /usr/local/lib/python3/dist-packages

WORKDIR /essentia
